name: CI

on:
  pull_request:
    branches: [ develop ]

jobs: 
  build:
    runs-on: ubuntu-lastest
    
    steps:
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0

    - name: CI Hello World
      run: echo 'Hello, world!'

    - name: Configuration Yarn
      run: yarn

    - name: Build Package
      run: yarn build:weapp
